<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search url
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["url/new", "Create url"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
echo $this->tag->form(
    [
        "url/search",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIcon" class="col-sm-2 control-label">Icon</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["icon", "size" => 30, "class" => "form-control", "id" => "fieldIcon"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldController" class="col-sm-2 control-label">Controller</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["controller", "size" => 30, "class" => "form-control", "id" => "fieldController"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAction" class="col-sm-2 control-label">Action</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["action", "size" => 30, "class" => "form-control", "id" => "fieldAction"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRoles" class="col-sm-2 control-label">Roles</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["roles", "size" => 30, "class" => "form-control", "id" => "fieldRoles"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
