<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["url/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["url/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Icon</th>
            <th>Title</th>
            <th>Controller</th>
            <th>Action</th>
            <th>Roles</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $url): ?>
            <tr>
                <td><?php echo $url->id ?></td>
                <td><?php echo $url->icon ?></td>
                <td><?php echo $url->title ?></td>
                <td><?php echo $url->controller ?></td>
                <td><?php echo $url->action ?></td>
                <td><?php echo $url->roles ?></td>

                <td><?php echo $this->tag->linkTo(["url/edit/" . $url->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["url/delete/" . $url->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("url/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("url/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("url/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("url/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
